name: bit_swap
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # Tools
  go_router: ^4.2.8
  flame: ^1.3.0
  flame_forge2d: ^0.12.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flame_lint: ^0.1.2
  intl_utils: ^2.7.0
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/audio/

  fonts:
    - family: PermanentMarker
      fonts:
        - asset: assets/fonts/permanent_marker/permanent_marker.ttf
    - family: MotionControl
      fonts:
        - asset: assets/fonts/motion_control/motion_control.otf


flutter_intl:
  enabled: true
  class_name: L10n

import_sorter:
  comments: false
